Autotag: 2022-09-06
Roam-Research/roam-depot pull request #186
Opened 2022-09-07 01:35 UTC by dvargas92495

2022-09-09 21:08 UTC, panterarocks49 requested changes
Is this the new home for page synonyms and unlink finder?
If so you might want to add some docs about how those work

unlink appears to be off but I am still getting some matches, is it off when the helper bar doesn't appear? or is it always on until I switch it off in settings? If it is on then it is not finding some of the matches
<img width="1814" alt="image" src="https://user-images.githubusercontent.com/23647837/189444210-03d02c9b-7132-4299-b92c-43da76c03075.png">

Also when I shut down unlink finder from the settings (see screenshot below, now there is no unlink finder button) it still shows the highlights, even after navigating to a new page
<img width="1805" alt="image" src="https://user-images.githubusercontent.com/23647837/189445600-29a89904-6505-4b9e-90a5-fd5b156b6b99.png">

I am planning on force updating everyone early next week, I am going to wait to merge this until then to make sure everyone has the code for returning a function from onload

2022-09-09 21:09 UTC, panterarocks49 commented
Another small thing that would be nice if it was fixed, unlink finder appears to not recognize that attributes are pages
<img width="187" alt="image" src="https://user-images.githubusercontent.com/23647837/189446186-6d6a1e39-4311-43a0-9e58-b9cff92f6d34.png">

2022-09-10 18:47 UTC, dvargas92495 commented
Yes this will be the new home for those extensions - I've updated the docs accordingly

It should turn off after you toggle it off and I saw the bug - Added a fix and also transcribed unlink finder to typescript since the js version was driving me nuts lol

Will look into the attribute issue next

2022-09-14 21:52 UTC, panterarocks49 approved these changes

2022-09-14 21:52 UTC, merged