new extension: power css pack
Roam-Research/roam-depot pull request #530
Opened 2023-02-12 18:19 UTC by dragonforce2010

2023-02-22 04:34 UTC, dragonforce2010 commented
onhold this mr for now, I need to add a detailed readme

2023-03-09 20:49 UTC, panterarocks49 commented on extensions/dragonforce2010/roam-power-css-pack.json
> +  "source_url": "https://github.com/dragonforce2010/roam-power-css-pack.git",
Can you update this to not have the .git at the end?

2023-03-12 11:41 UTC, dragonforce2010 commented on extensions/dragonforce2010/roam-power-css-pack.json
> +  "source_url": "https://github.com/dragonforce2010/roam-power-css-pack.git",
sure, will do it:)

2023-04-16 15:31 UTC, dragonforce2010 commented
can anyone review this pr?

2023-04-26 10:57 UTC, baibhavbista requested changes
Hey @dragonforce2010 

Again, sorry for the delay in reviewing the extensions

I have a couple of comments:

1. I _really_ don't like that you're creating new css classes starting with `rm-`. The reason is that we (the roam team) are using that convention for our CSS classes. If you also create new classes with the same naming scheme, it can easily lead to issues in the future if we add classes named the same as yours (mistakenly). Would like it if you renamed all of the new css classes starting with `rm-`, like `rm-bg-level`, `rm-grid`, `rm-border`, etc

2. Would prefer that the extension only loads the css on the `onload` and cleans up the CSS pm the `onunload` function

3. Personal review: I was trying to use your extension since some of the css classes looked useful. However, right out of the box, it installed a theme which I personally did not like. Would prefer if it did not include any theme.
<img width="308" alt="image" src="https://user-images.githubusercontent.com/23657255/234554907-d2b1dc5c-8cd4-4346-8a42-2e7f652c95d4.png">

2023-04-26 17:32 UTC, dragonforce2010 commented
@baibhavbista thanks for the comments and please check out the latest pr, all comments have been addressed.

2023-05-05 07:09 UTC, baibhavbista reviewed
Hey @dragonforce2010 

thanks for taking care of the first 2 things I mentioned in the earlier review: https://github.com/Roam-Research/roam-depot/pull/530#pullrequestreview-1401727373

I saw that you did not do number 3 (disable rainbow theme). My rationale for that was that I'd expect most users would not want that theme. Were you not able to factor it out of the extension?

2023-05-05 07:29 UTC, dragonforce2010 commented
> 

I have removed rainbow.css from my code in my current pr, can you check again?

2023-05-05 08:10 UTC, baibhavbista commented
@dragonforce2010 oh sorry I mistakenly called it rainbow.css

By the "theme"/"rainbow theme", I meant this thing where it auto sets the color of each level of blocks in the graph. If you want it, I think you could make it a setting, or even better, only activated when a css class like .css-rainbow-children is used. My feeling is that most users will not want it on by default. 

<img width="707" alt="image" src="https://user-images.githubusercontent.com/23657255/236406486-4439a9c9-9f33-4fcd-96d2-72faac89c9c1.png">

The POV I'm looking at this extension through is that as a user, I can use the css classes provided by this extension as I need it and ONLY then. Since it's a power pack, I wouldn't expect to change default behavior of any code. If I wanted default behavior, I'd expect that from a theme extension. Hope that makes sense

2023-05-06 06:05 UTC, dragonforce2010 commented
> @dragonforce2010 oh sorry I mistakenly called it rainbow.css
> 
> By the "theme"/"rainbow theme", I meant this thing where it auto sets the color of each level of blocks in the graph. If you want it, I think you could make it a setting, or even better, only activated when a css class like .css-rainbow-children is used. My feeling is that most users will not want it on by default.
> 
> <img alt="image" width="707" src="https://user-images.githubusercontent.com/23657255/236406486-4439a9c9-9f33-4fcd-96d2-72faac89c9c1.png">
> 
> The POV I'm looking at this extension through is that as a user, I can use the css classes provided by this extension as I need it and ONLY then. Since it's a power pack, I wouldn't expect to change default behavior of any code. If I wanted default behavior, I'd expect that from a theme extension. Hope that makes sense

good catch, comments has been addressed, as per your suggestion, the font level color will be only activate when putting `#.css-level-color`

2023-05-15 06:11 UTC, baibhavbista commented
thanks for fixing, @dragonforce2010. everything looks good to me now, will publish

2023-05-15 06:11 UTC, merged