Roam Memo: Release v18
Roam-Research/roam-depot pull request #934
Opened 2024-10-13 16:43 UTC by digitalmaster

2024-11-04 18:58 UTC, panterarocks49 commented
Hey @digitalmaster did you mean to mark this as a draft?

2024-11-04 20:46 UTC, digitalmaster commented
Yea there's a bug I found that I want to address before this gets merged. 🙏🏽

2024-11-27 14:12 UTC, digitalmaster commented
@panterarocks49 We're good to review/merge now. Thanks a lot 🙏🏽

2025-01-02 09:21 UTC, baibhavbista requested changes
@digitalmaster when testing on a new graph, found some bugs, please fix and also test extensively
Do let me know if you need any help!

Loom video showing the issues: https://www.loom.com/share/20f73761cb5a4d569b547ccc11968472
(should be okay to watch on 2x)

2025-01-03 16:59 UTC, digitalmaster commented
Thanks for testing this thoroughly and creating the loom @baibhavbista... I think your right that this is due to me forgetting to add tests for case where data page hasn't been created yet (completely ignored that in my testing 😆). Also, I think you found a pre-existing bug (I just confirmed that this happens in published version as well). 

I'll have a patch for this with new tests ready to review soon.

2025-01-08 12:22 UTC, merged