fix: perf up
Roam-Research/roam-depot pull request #962
Opened 2024-12-18 14:59 UTC by dive2Pro

2025-01-02 06:56 UTC, baibhavbista commented
Hey @dive2Pro , 

some comments:

**1. README images not working**

you can check via `(?)`
![image](https://github.com/user-attachments/assets/874ff35c-d80b-4a5b-9bde-5a61e714a12e)

changing the readme like this would make it work I think
![image](https://github.com/user-attachments/assets/90125e7c-0ae7-415b-b30e-7204d5b16482)


2. I've also DM'd you in Slack a loom showing slowdowns when using the extension when doing things like opening the sidebar. Can you check in a graph which has a lot of data in [[roam/reference extends/config]] and see if you can reproduce this on the old version and if it's better on the new version?

2025-01-02 07:01 UTC, baibhavbista requested changes
https://github.com/Roam-Research/roam-depot/pull/962#issuecomment-2567348517

2025-01-04 03:53 UTC, dive2Pro commented
@baibhavbista 
1. Fixed.
2. Yes, I can reproduce this issue in the old version. I confirm that this problem should not occur in the newer version.

2025-01-08 12:14 UTC, baibhavbista commented
awesome @dive2Pro 
Thanks, I will release
btw I encountered a bug(?) where this extension does not seem to work with refs of blocks containing `>` I think? Can you check? https://www.loom.com/share/450ae7ce425949c7a943ab7c909b4277

2025-01-08 12:14 UTC, merged