Update todo-progress-bar.json
Roam-Research/roam-depot pull request #965
Opened 2024-12-30 15:39 UTC by 8bitgentleman

adds an option for both horizontal progress bars as well as radial progress bars 

![image](https://github.com/user-attachments/assets/949a4e66-db1b-416c-8894-7cf509c41612)

Just pass in "radial" to the component to try `{{[[roam/render]]:((roam-render-todo-progress-bar-cljs)) "radial"}}`

2025-01-02 05:56 UTC, baibhavbista commented
Hey @8bitgentleman, my review below:

**1.** Main issue I see is that this change changes the uid of the blocks, both the code and css blocks
<img width="1425" alt="image" src="https://github.com/user-attachments/assets/a1ebb14c-c65e-4815-a7e1-81b0cdb0d0cf" />

For example, the `codeBlockUid` would change from `roam-render-todo-progress-cljs` to `roam-render-todo-progress-bar-cljs`

What effect would that have on the old code blocks from before this release?

**2. ** (Optional but would be good to have) I think @tombarys and I ran into a better way of setting-up/tearing-down extensions which have roam render components. Could you take a look?
Some resources:
i. I think this is the relevant roam-depot PR: https://github.com/Roam-Research/roam-depot/pull/869 . And here is the code diff: https://github.com/tombarys/roam-depot-nautilus/compare/08152fd8807663f19b95cd98e88b07b74f4fd38e..e499bb60443abe879d762cbab8c901331d0d0295
ii. Here is (at least part of) the change: https://github.com/tombarys/roam-depot-nautilus/pull/7 . I have a loom video in this link which I think should be enough for you to understand the solution
If you have any questions, feel free to ask away

2025-01-02 07:00 UTC, baibhavbista requested changes
https://github.com/Roam-Research/roam-depot/pull/965#issuecomment-2567312644

2025-01-02 13:52 UTC, 8bitgentleman commented
@baibhavbista thanks for catching this!! The uid change was definitely accidental. I've also made the load/unload updates mentioned (I believe). I tested and it seemed to work

2025-01-08 11:34 UTC, baibhavbista commented
@8bitgentleman  thanks
everything looks good now
And yeah, the load/unload updates looks good too!
will release now

2025-01-08 11:34 UTC, merged